export enum ProjetoStatusEnum {
  ANALISE = "ANALISE",
  ANALISE_REALIZADA = "ANALISE_REALIZADA",
  ANALISE_APROVADA = "ANALISE_APROVADA",
  INICIADO = "INICIADO",
  PLANEJADO = "PLANEJADO",
  EM_ANDAMENTO = "EM_ANDAMENTO",
  ENCERRADO = "ENCERRADO",
  CANCELADO = "CANCELADO",
}
